### ISSUE TITLE
Cannot callback after payment in whmcs8.1.3 version

### ISSUE THREAD

**Issue by Nadenesmith1221** [edgesite/whmcs-nihaopay#1]
Cannot callback after payment in whmcs8.1.3 version

**Comment by uniglobe1** [comment]
@Nadenesmith1221 See the Pull Request that was just submitted. This resolved a main issue with the callback for me and I am running WHMCS on 8.1.3.

However your issue describes very little, so maybe you are referring to something else.

**Comment by edgesite** [comment]
It should fixed by https://github.com/edgesite/whmcs-nihaopay/commit/e771994d078f3e7ecf6db0104b00b99105b41038
